---
title: "assignment start"
author: "Sören Twietmeyer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
#Set Directory as appropriate
#setwd("C/...")
library(jsonlite)
```


```{r}
#Pre-Processing Yelp Academic Data for the Assignment
#Clear
cat("\014")  
rm(list=ls())


#Load Different Data
business_data <- stream_in(file("../data/yelp_academic_dataset_business.json")) #note that stream_in reads the json lines (as the files are json lines, not json)
review_data  <- stream_in(file("../data/yelp_academic_dataset_review.json")) #note that stream_in reads the json lines (as the files are json lines, not json)
checkin_data  <- stream_in(file("../data/yelp_academic_dataset_checkin.json")) #note that stream_in reads the json lines (as the files are json lines, not json)
user_data <- stream_in(file("../data/yelp_academic_dataset_user.json")) #note that stream_in reads the json lines (as the files are json lines, not json)
tip_data  <- stream_in(file("../data/yelp_academic_dataset_tip.json")) #note that stream_in reads the json lines (as the files are json lines, not json)

```

